# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/durant/star_type/ui/main.ui'
#
# Created: Tue May 31 16:55:54 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 493)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Output = QtGui.QPlainTextEdit(self.centralwidget)
        self.Output.setObjectName("Output")
        self.verticalLayout.addWidget(self.Output)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.Ubox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Ubox.setProperty("value", 25.0)
        self.Ubox.setObjectName("Ubox")
        self.horizontalLayout_2.addWidget(self.Ubox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.Bbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Bbox.setProperty("value", 25.0)
        self.Bbox.setObjectName("Bbox")
        self.horizontalLayout_2.addWidget(self.Bbox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Vbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Vbox.setProperty("value", 25.0)
        self.Vbox.setObjectName("Vbox")
        self.horizontalLayout_2.addWidget(self.Vbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Rbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Rbox.setProperty("value", 25.0)
        self.Rbox.setObjectName("Rbox")
        self.horizontalLayout_2.addWidget(self.Rbox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.Ibox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Ibox.setProperty("value", 25.0)
        self.Ibox.setObjectName("Ibox")
        self.horizontalLayout_2.addWidget(self.Ibox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Jbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Jbox.setProperty("value", 25.0)
        self.Jbox.setObjectName("Jbox")
        self.horizontalLayout_2.addWidget(self.Jbox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.Hbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Hbox.setProperty("value", 25.0)
        self.Hbox.setObjectName("Hbox")
        self.horizontalLayout_2.addWidget(self.Hbox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.Kbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.Kbox.setProperty("value", 25.0)
        self.Kbox.setObjectName("Kbox")
        self.horizontalLayout_2.addWidget(self.Kbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.Ubox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Ubox_2.setMinimum(0.01)
        self.Ubox_2.setMaximum(1.0)
        self.Ubox_2.setSingleStep(0.1)
        self.Ubox_2.setProperty("value", 1.0)
        self.Ubox_2.setObjectName("Ubox_2")
        self.horizontalLayout_5.addWidget(self.Ubox_2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.Bbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Bbox_2.setMinimum(0.01)
        self.Bbox_2.setMaximum(1.0)
        self.Bbox_2.setSingleStep(0.1)
        self.Bbox_2.setProperty("value", 1.0)
        self.Bbox_2.setObjectName("Bbox_2")
        self.horizontalLayout_5.addWidget(self.Bbox_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.Vbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Vbox_2.setMinimum(0.01)
        self.Vbox_2.setMaximum(1.0)
        self.Vbox_2.setSingleStep(0.1)
        self.Vbox_2.setProperty("value", 1.0)
        self.Vbox_2.setObjectName("Vbox_2")
        self.horizontalLayout_5.addWidget(self.Vbox_2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.Rbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Rbox_2.setMinimum(0.01)
        self.Rbox_2.setMaximum(1.0)
        self.Rbox_2.setSingleStep(0.1)
        self.Rbox_2.setProperty("value", 1.0)
        self.Rbox_2.setObjectName("Rbox_2")
        self.horizontalLayout_5.addWidget(self.Rbox_2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.Ibox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Ibox_2.setMinimum(0.01)
        self.Ibox_2.setMaximum(1.0)
        self.Ibox_2.setSingleStep(0.1)
        self.Ibox_2.setProperty("value", 1.0)
        self.Ibox_2.setObjectName("Ibox_2")
        self.horizontalLayout_5.addWidget(self.Ibox_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.Jbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Jbox_2.setMinimum(0.01)
        self.Jbox_2.setMaximum(1.0)
        self.Jbox_2.setSingleStep(0.1)
        self.Jbox_2.setProperty("value", 1.0)
        self.Jbox_2.setObjectName("Jbox_2")
        self.horizontalLayout_5.addWidget(self.Jbox_2)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.Hbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Hbox_2.setMinimum(0.01)
        self.Hbox_2.setMaximum(1.0)
        self.Hbox_2.setSingleStep(0.1)
        self.Hbox_2.setProperty("value", 1.0)
        self.Hbox_2.setObjectName("Hbox_2")
        self.horizontalLayout_5.addWidget(self.Hbox_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.Kbox_2 = QtGui.QDoubleSpinBox(self.frame)
        self.Kbox_2.setMinimum(0.01)
        self.Kbox_2.setMaximum(1.0)
        self.Kbox_2.setSingleStep(0.1)
        self.Kbox_2.setProperty("value", 1.0)
        self.Kbox_2.setObjectName("Kbox_2")
        self.horizontalLayout_5.addWidget(self.Kbox_2)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TeffBox = QtGui.QComboBox(self.centralwidget)
        self.TeffBox.setObjectName("TeffBox")
        self.TeffBox.addItem("")
        self.horizontalLayout_3.addWidget(self.TeffBox)
        self.logZBox = QtGui.QComboBox(self.centralwidget)
        self.logZBox.setObjectName("logZBox")
        self.logZBox.addItem("")
        self.horizontalLayout_3.addWidget(self.logZBox)
        self.loggBox = QtGui.QComboBox(self.centralwidget)
        self.loggBox.setObjectName("loggBox")
        self.loggBox.addItem("")
        self.horizontalLayout_3.addWidget(self.loggBox)
        self.EbvBox = QtGui.QComboBox(self.centralwidget)
        self.EbvBox.setObjectName("EbvBox")
        self.EbvBox.addItem("")
        self.horizontalLayout_3.addWidget(self.EbvBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calculateButton = QtGui.QPushButton(self.centralwidget)
        self.calculateButton.setObjectName("calculateButton")
        self.horizontalLayout.addWidget(self.calculateButton)
        self.plotButton = QtGui.QPushButton(self.centralwidget)
        self.plotButton.setObjectName("plotButton")
        self.horizontalLayout.addWidget(self.plotButton)
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.loadButton = QtGui.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_8.setBuddy(self.Ubox)
        self.label.setBuddy(self.Bbox)
        self.label_2.setBuddy(self.Vbox)
        self.label_3.setBuddy(self.Rbox)
        self.label_4.setBuddy(self.Ibox)
        self.label_5.setBuddy(self.Jbox)
        self.label_6.setBuddy(self.Hbox)
        self.label_7.setBuddy(self.Kbox)
        self.label_15.setBuddy(self.Ubox)
        self.label_12.setBuddy(self.Bbox)
        self.label_11.setBuddy(self.Vbox)
        self.label_14.setBuddy(self.Rbox)
        self.label_9.setBuddy(self.Ibox)
        self.label_13.setBuddy(self.Jbox)
        self.label_10.setBuddy(self.Hbox)
        self.label_16.setBuddy(self.Kbox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Ubox, self.Bbox)
        MainWindow.setTabOrder(self.Bbox, self.Vbox)
        MainWindow.setTabOrder(self.Vbox, self.Rbox)
        MainWindow.setTabOrder(self.Rbox, self.Ibox)
        MainWindow.setTabOrder(self.Ibox, self.Jbox)
        MainWindow.setTabOrder(self.Jbox, self.Hbox)
        MainWindow.setTabOrder(self.Hbox, self.Kbox)
        MainWindow.setTabOrder(self.Kbox, self.calculateButton)
        MainWindow.setTabOrder(self.calculateButton, self.plotButton)
        MainWindow.setTabOrder(self.plotButton, self.clearButton)
        MainWindow.setTabOrder(self.clearButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.Output)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Star Typer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "dU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "dB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "dV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "dR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "dI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "dJ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "dH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "dK", None, QtGui.QApplication.UnicodeUTF8))
        self.TeffBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Teff - free", None, QtGui.QApplication.UnicodeUTF8))
        self.logZBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "log Z - free", None, QtGui.QApplication.UnicodeUTF8))
        self.loggBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "log g - free", None, QtGui.QApplication.UnicodeUTF8))
        self.EbvBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "E(B-V) - free", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateButton.setText(QtGui.QApplication.translate("MainWindow", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("MainWindow", "Load Data", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

